//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZ.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public int Id { get; set; }
        public System.DateTime SDate { get; set; }
        public int SDocNumber { get; set; }
        public int CustomerId { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public string Appartment { get; set; }
        public int MtId { get; set; }
        public int MtQty { get; set; }
        public decimal MtPrice { get; set; }
        public string Comment { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual User User { get; set; }
    }
}
