//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZ.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserCartProduct
    {
        public int Id { get; set; }
        public int UserCartId { get; set; }
        public int ProductId { get; set; }
        public int Qty { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual UserCart UserCart { get; set; }
    }
}
