//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectZ.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserToConfirm
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public string PostalCode { get; set; }
        public string Appartment { get; set; }
        public string ConfirmationCode { get; set; }
        public Nullable<bool> IsAdministrator { get; set; }
        public System.DateTime CreationDate { get; set; }
    }
}
